version: '3.3'

services:
  app_server:
    build: dev-ops/docker/containers/app
    links:
      - app_mysql:mysql
      - smtp:smtp
    volumes:
      - .:/app
      - ~/.composer/cache:/.composer/cache

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  selenium:
    image: selenium/standalone-chrome:3.8
    shm_size: 2g

  smtp:
    image: mailhog/mailhog
