#override defaults for dev
version: "3.3"

services:
  app_server:
    ports:
      - "8088:80"

  app_mysql:
    ports:
      - "4407:3306"
    volumes:
      - ./dev-ops/docker/_volumes/mysql:/var/lib/mysql
