name: Check Code

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install github:cachix/devenv/v0.5
      shell: sh
    - run: devenv up &
    - run: devenv shell init-shopware
    - run: devenv shell check-code
